"""
One-time code generation and verification (Figure 3.1, "MFA / TOTP Verification").

Uses the pyotp library, which implements RFC 6238 (Time-based One-Time
Password). This is the possession factor: a code that changes every 30
seconds and is generated by a standard authenticator application.
"""
import pyotp


def generate_secret() -> str:
    """Create a new random base32 secret for a user during registration."""
    return pyotp.random_base32()


def provisioning_uri(username: str, secret: str, issuer: str = "MFA Prototype") -> str:
    """Build the otpauth:// URI used to render a QR code for the
    authenticator app during setup."""
    return pyotp.totp.TOTP(secret).provisioning_uri(name=username, issuer_name=issuer)


def verify_code(secret: str, code: str, valid_window: int = 1) -> bool:
    """Check a submitted one-time code against the secret.

    valid_window=1 allows the previous and next 30-second window, matching
    Figure 3.2 ("Code valid and not expired?") so that small clock drift
    between the server and the user's phone does not cause a false rejection.
    """
    totp = pyotp.totp.TOTP(secret)
    return totp.verify(code, valid_window=valid_window)
